// Generated by scripts/export_demo_data.py. Do not edit by hand.

export const DEMO_META = {
  "datasetLabel": "October 2019 purchase export",
  "sessionId": "0000de39-dc74-414d-8da6-83ad56135bf5",
  "sessionProductCount": 4,
  "note": "Labels and thumbnails are derived from product_id, brand, category_code, and price because the source dataset does not include product titles or product photos."
} as const;

export const HISTORY = [
  {
    "id": "1004246",
    "title": "Apple Smartphone #1004246",
    "category": "Electronics / Smartphone",
    "time": "11:08 UTC",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%237c2d12%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ea580c%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004246%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24736.18%3C/text%3E%0A%3C/svg%3E"
  },
  {
    "id": "1002544",
    "title": "Apple Smartphone #1002544",
    "category": "Electronics / Smartphone",
    "time": "11:10 UTC",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%2314532d%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2316a34a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201002544%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24464.13%3C/text%3E%0A%3C/svg%3E"
  },
  {
    "id": "1004767",
    "title": "Samsung Smartphone #1004767",
    "category": "Electronics / Smartphone",
    "time": "11:12 UTC",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23581c87%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23c026d3%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004767%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24254.82%3C/text%3E%0A%3C/svg%3E"
  },
  {
    "id": "1004833",
    "title": "Samsung Smartphone #1004833",
    "category": "Electronics / Smartphone",
    "time": "11:15 UTC",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23312e81%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%236366f1%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004833%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24174.76%3C/text%3E%0A%3C/svg%3E"
  }
] as const;

export const PRODUCT_DETAILS = {
  "1004246": {
    "id": "1004246",
    "title": "Apple Smartphone #1004246",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%237c2d12%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ea580c%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004246%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24736.18%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Apple in Electronics / Smartphone at a listed price of $736.18.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1004246 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 2,248.",
    "attributes": [
      "Product 1004246",
      "Apple",
      "Smartphone",
      "$736.18"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "2,248"
      },
      {
        "label": "Brand",
        "value": "Apple"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Session purchase 1 of 4"
      }
    ]
  },
  "1002544": {
    "id": "1002544",
    "title": "Apple Smartphone #1002544",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%2314532d%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2316a34a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201002544%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24464.13%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Apple in Electronics / Smartphone at a listed price of $464.13.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1002544 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 10,549.",
    "attributes": [
      "Product 1002544",
      "Apple",
      "Smartphone",
      "$464.13"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "10,549"
      },
      {
        "label": "Brand",
        "value": "Apple"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Session purchase 2 of 4"
      }
    ]
  },
  "1004767": {
    "id": "1004767",
    "title": "Samsung Smartphone #1004767",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23581c87%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23c026d3%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004767%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24254.82%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Samsung in Electronics / Smartphone at a listed price of $254.82.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1004767 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 21,806.",
    "attributes": [
      "Product 1004767",
      "Samsung",
      "Smartphone",
      "$254.82"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "21,806"
      },
      {
        "label": "Brand",
        "value": "Samsung"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Session purchase 3 of 4"
      }
    ]
  },
  "1004833": {
    "id": "1004833",
    "title": "Samsung Smartphone #1004833",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23312e81%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%236366f1%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004833%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24174.76%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Samsung in Electronics / Smartphone at a listed price of $174.76.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1004833 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 12,697.",
    "attributes": [
      "Product 1004833",
      "Samsung",
      "Smartphone",
      "$174.76"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "12,697"
      },
      {
        "label": "Brand",
        "value": "Samsung"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Session purchase 4 of 4"
      }
    ]
  },
  "1004856": {
    "id": "1004856",
    "title": "Samsung Smartphone #1004856",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%237c2d12%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ea580c%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004856%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24130.76%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Samsung in Electronics / Smartphone at a listed price of $130.76.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1004856 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 28,944.",
    "attributes": [
      "Product 1004856",
      "Samsung",
      "Smartphone",
      "$130.76"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "28,944"
      },
      {
        "label": "Brand",
        "value": "Samsung"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Recommended candidate"
      }
    ]
  },
  "1005115": {
    "id": "1005115",
    "title": "Apple Smartphone #1005115",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201005115%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24975.57%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Apple in Electronics / Smartphone at a listed price of $975.57.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1005115 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 12,543.",
    "attributes": [
      "Product 1005115",
      "Apple",
      "Smartphone",
      "$975.57"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "12,543"
      },
      {
        "label": "Brand",
        "value": "Apple"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Recommended candidate"
      }
    ]
  },
  "4804056": {
    "id": "4804056",
    "title": "Apple Headphone #4804056",
    "category": "Electronics / Audio / Headphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EHEADPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%204804056%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24161.98%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Apple in Electronics / Audio / Headphone at a listed price of $161.98.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 4804056 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 12,381.",
    "attributes": [
      "Product 4804056",
      "Apple",
      "Headphone",
      "$161.98"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "12,381"
      },
      {
        "label": "Brand",
        "value": "Apple"
      },
      {
        "label": "Category",
        "value": "Electronics / Audio / Headphone"
      },
      {
        "label": "Session role",
        "value": "Recommended candidate"
      }
    ]
  },
  "1004870": {
    "id": "1004870",
    "title": "Samsung Smartphone #1004870",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004870%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24286.86%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Samsung in Electronics / Smartphone at a listed price of $286.86.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1004870 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 10,615.",
    "attributes": [
      "Product 1004870",
      "Samsung",
      "Smartphone",
      "$286.86"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "10,615"
      },
      {
        "label": "Brand",
        "value": "Samsung"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Recommended candidate"
      }
    ]
  },
  "1004249": {
    "id": "1004249",
    "title": "Apple Smartphone #1004249",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004249%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24739.81%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Apple in Electronics / Smartphone at a listed price of $739.81.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1004249 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 9,090.",
    "attributes": [
      "Product 1004249",
      "Apple",
      "Smartphone",
      "$739.81"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "9,090"
      },
      {
        "label": "Brand",
        "value": "Apple"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Recommended candidate"
      }
    ]
  },
  "1004836": {
    "id": "1004836",
    "title": "Samsung Smartphone #1004836",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23164e63%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%230891b2%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004836%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24241.19%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Samsung in Electronics / Smartphone at a listed price of $241.19.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1004836 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 7,691.",
    "attributes": [
      "Product 1004836",
      "Samsung",
      "Smartphone",
      "$241.19"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "7,691"
      },
      {
        "label": "Brand",
        "value": "Samsung"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Recommended candidate"
      }
    ]
  },
  "1002633": {
    "id": "1002633",
    "title": "Apple Smartphone #1002633",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23164e63%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%230891b2%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201002633%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24360.08%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Apple in Electronics / Smartphone at a listed price of $360.08.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1002633 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 5,301.",
    "attributes": [
      "Product 1002633",
      "Apple",
      "Smartphone",
      "$360.08"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "5,301"
      },
      {
        "label": "Brand",
        "value": "Apple"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Recommended candidate"
      }
    ]
  },
  "1004750": {
    "id": "1004750",
    "title": "Samsung Smartphone #1004750",
    "category": "Electronics / Smartphone",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%237c2d12%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ea580c%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004750%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24197.43%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Recorded as Samsung in Electronics / Smartphone at a listed price of $197.43.",
    "description": "The source dataset does not include product titles or product photos, so this demo labels item 1004750 from the recorded brand, category, and price fields. Observed purchase volume in the October 2019 extract: 4,597.",
    "attributes": [
      "Product 1004750",
      "Samsung",
      "Smartphone",
      "$197.43"
    ],
    "facts": [
      {
        "label": "Purchases",
        "value": "4,597"
      },
      {
        "label": "Brand",
        "value": "Samsung"
      },
      {
        "label": "Category",
        "value": "Electronics / Smartphone"
      },
      {
        "label": "Session role",
        "value": "Recommended candidate"
      }
    ]
  }
} as const;

export const RECOMMENDATIONS = {
  "popularity": [
    {
      "id": "1004856",
      "title": "Samsung Smartphone #1004856",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%237c2d12%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ea580c%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004856%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24130.76%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Purchased 28,944 times overall. Brand Samsung appears in Electronics / Smartphone at a listed price of $130.76.",
      "score": "28,944",
      "scoreLabel": "Purchases",
      "signals": [
        {
          "label": "Volume idx",
          "value": 100,
          "color": "bg-emerald-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        },
        {
          "label": "Brand fit",
          "value": 100,
          "color": "bg-amber-500"
        }
      ],
      "tags": [
        {
          "label": "Top purchases",
          "type": "popularity"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "1005115",
      "title": "Apple Smartphone #1005115",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201005115%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24975.57%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Purchased 12,543 times overall. Brand Apple appears in Electronics / Smartphone at a listed price of $975.57.",
      "score": "12,543",
      "scoreLabel": "Purchases",
      "signals": [
        {
          "label": "Volume idx",
          "value": 43,
          "color": "bg-emerald-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        },
        {
          "label": "Brand fit",
          "value": 100,
          "color": "bg-amber-500"
        }
      ],
      "tags": [
        {
          "label": "Top purchases",
          "type": "popularity"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "4804056",
      "title": "Apple Headphone #4804056",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EHEADPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%204804056%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24161.98%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Purchased 12,381 times overall. Brand Apple appears in Electronics / Audio / Headphone at a listed price of $161.98.",
      "score": "12,381",
      "scoreLabel": "Purchases",
      "signals": [
        {
          "label": "Volume idx",
          "value": 43,
          "color": "bg-emerald-500"
        },
        {
          "label": "Category fit",
          "value": 70,
          "color": "bg-cyan-500"
        },
        {
          "label": "Brand fit",
          "value": 100,
          "color": "bg-amber-500"
        }
      ],
      "tags": [
        {
          "label": "Top purchases",
          "type": "popularity"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "1004870",
      "title": "Samsung Smartphone #1004870",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004870%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24286.86%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Purchased 10,615 times overall. Brand Samsung appears in Electronics / Smartphone at a listed price of $286.86.",
      "score": "10,615",
      "scoreLabel": "Purchases",
      "signals": [
        {
          "label": "Volume idx",
          "value": 37,
          "color": "bg-emerald-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        },
        {
          "label": "Brand fit",
          "value": 100,
          "color": "bg-amber-500"
        }
      ],
      "tags": [
        {
          "label": "Top purchases",
          "type": "popularity"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "1004249",
      "title": "Apple Smartphone #1004249",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004249%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24739.81%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Purchased 9,090 times overall. Brand Apple appears in Electronics / Smartphone at a listed price of $739.81.",
      "score": "9,090",
      "scoreLabel": "Purchases",
      "signals": [
        {
          "label": "Volume idx",
          "value": 31,
          "color": "bg-emerald-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        },
        {
          "label": "Brand fit",
          "value": 100,
          "color": "bg-amber-500"
        }
      ],
      "tags": [
        {
          "label": "Top purchases",
          "type": "popularity"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    }
  ],
  "item_item": [
    {
      "id": "1004856",
      "title": "Samsung Smartphone #1004856",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%237c2d12%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ea580c%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004856%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24130.76%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Co-purchased in 1,101 sessions with 4 of the 4 products in the selected October session.",
      "score": "1,101",
      "scoreLabel": "Co-sessions",
      "signals": [
        {
          "label": "Co-session idx",
          "value": 100,
          "color": "bg-blue-500"
        },
        {
          "label": "Seed overlap",
          "value": 100,
          "color": "bg-indigo-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        }
      ],
      "tags": [
        {
          "label": "4/4 seed overlap",
          "type": "coview"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "1004870",
      "title": "Samsung Smartphone #1004870",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004870%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24286.86%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Co-purchased in 425 sessions with 4 of the 4 products in the selected October session.",
      "score": "425",
      "scoreLabel": "Co-sessions",
      "signals": [
        {
          "label": "Co-session idx",
          "value": 39,
          "color": "bg-blue-500"
        },
        {
          "label": "Seed overlap",
          "value": 100,
          "color": "bg-indigo-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        }
      ],
      "tags": [
        {
          "label": "4/4 seed overlap",
          "type": "coview"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "1004836",
      "title": "Samsung Smartphone #1004836",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23164e63%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%230891b2%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004836%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24241.19%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Co-purchased in 388 sessions with 4 of the 4 products in the selected October session.",
      "score": "388",
      "scoreLabel": "Co-sessions",
      "signals": [
        {
          "label": "Co-session idx",
          "value": 35,
          "color": "bg-blue-500"
        },
        {
          "label": "Seed overlap",
          "value": 100,
          "color": "bg-indigo-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        }
      ],
      "tags": [
        {
          "label": "4/4 seed overlap",
          "type": "coview"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "1002633",
      "title": "Apple Smartphone #1002633",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23164e63%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%230891b2%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EAPPLE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201002633%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24360.08%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Co-purchased in 288 sessions with 4 of the 4 products in the selected October session.",
      "score": "288",
      "scoreLabel": "Co-sessions",
      "signals": [
        {
          "label": "Co-session idx",
          "value": 26,
          "color": "bg-blue-500"
        },
        {
          "label": "Seed overlap",
          "value": 100,
          "color": "bg-indigo-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        }
      ],
      "tags": [
        {
          "label": "4/4 seed overlap",
          "type": "coview"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "1004750",
      "title": "Samsung Smartphone #1004750",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%237c2d12%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ea580c%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESAMSUNG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESMARTPHONE%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2228%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EID%201004750%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E%24197.43%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Co-purchased in 270 sessions with 4 of the 4 products in the selected October session.",
      "score": "270",
      "scoreLabel": "Co-sessions",
      "signals": [
        {
          "label": "Co-session idx",
          "value": 25,
          "color": "bg-blue-500"
        },
        {
          "label": "Seed overlap",
          "value": 100,
          "color": "bg-indigo-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        }
      ],
      "tags": [
        {
          "label": "4/4 seed overlap",
          "type": "coview"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    }
  ]
} as const;

export const HOW_IT_WORKS_STEPS = [
  {
    "title": "Replay one real purchase session",
    "body": "The left rail replays 4 products from a real October 2019 purchase session stored in the local SQLite export."
  },
  {
    "title": "Compare two ranking methods",
    "body": "Popularity ranks products by total purchase volume, while Item-Item CF ranks products by how often they were co-purchased with this session's products."
  },
  {
    "title": "Surface real evidence",
    "body": "Each recommendation shows recorded purchase counts, co-session counts, brand/category fit, and price metadata from the underlying dataset."
  }
] as const;

export const MODEL_EXPLANATIONS = [
  {
    "id": "popularity",
    "title": "Popularity",
    "eyebrow": "Purchase volume",
    "summary": "A global baseline that sorts products by total purchase count across the October 2019 extract.",
    "signals": [
      "Purchase count",
      "Category fit",
      "Brand fit"
    ]
  },
  {
    "id": "item_item",
    "title": "Item-Item CF",
    "eyebrow": "Co-purchase graph",
    "summary": "A behavioral model that ranks products by how often they appear in the same purchase sessions as the products in the selected session.",
    "signals": [
      "Co-session count",
      "Seed overlap",
      "Category fit"
    ]
  }
] as const;

export default {
  DEMO_META,
  HISTORY,
  PRODUCT_DETAILS,
  RECOMMENDATIONS,
  HOW_IT_WORKS_STEPS,
  MODEL_EXPLANATIONS,
} as const;
