// Generated by scripts/export_demo_data.py. Do not edit by hand.

export const DEMO_META = {
  "datasetLabel": "Myket Android app install interactions",
  "sessionId": "-1003884945",
  "historyAppCount": 6,
  "note": "This demo uses anonymized user-app install events from Myket. App cards are derived from package name, category, install-count, and rating metadata because the dataset does not include app icons or marketing screenshots."
} as const;

export const HISTORY = [
  {
    "id": "ir.tv.off",
    "title": "TV OFF",
    "category": "Educational",
    "time": "t+4,233,794",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ETV%20OFF%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EEDUCATIONAL%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EOFF%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E2.36%20rating%3C/text%3E%0A%3C/svg%3E"
  },
  {
    "id": "com.farakav.anten",
    "title": "Farakav Anten",
    "category": "Utility",
    "time": "t+4,233,996",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23581c87%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23c026d3%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EFARAKAV%20ANTEN%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EUTILITY%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EANTEN%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.60%20rating%3C/text%3E%0A%3C/svg%3E"
  },
  {
    "id": "com.incytel.mencherz",
    "title": "Incytel Mencherz",
    "category": "Family",
    "time": "t+5,151,066",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23164e63%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%230891b2%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EINCYTEL%20MENCHERZ%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EFAMILY%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EMENCHERZ%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.26%20rating%3C/text%3E%0A%3C/svg%3E"
  },
  {
    "id": "com.ParsisGames.AirCombat",
    "title": "Parsis Games AIR",
    "category": "Thrilling",
    "time": "t+5,151,724",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23581c87%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23c026d3%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EPARSIS%20GAMES%20AIR%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ETHRILLING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EAIRCOMBAT%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.70%20rating%3C/text%3E%0A%3C/svg%3E"
  },
  {
    "id": "com.StudioBadbadak.Khastegaran",
    "title": "Studio Badbadak Khastegaran",
    "category": "Artistic",
    "time": "t+5,266,775",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23164e63%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%230891b2%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESTUDIO%20BADBADAK%20KH%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EARTISTIC%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EKHASTEGARAN%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.35%20rating%3C/text%3E%0A%3C/svg%3E"
  },
  {
    "id": "com.digikala",
    "title": "Digikala",
    "category": "Shopping",
    "time": "t+5,442,002",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23581c87%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23c026d3%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EDIGIKALA%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESHOPPING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EDIGIKALA%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.49%20rating%3C/text%3E%0A%3C/svg%3E"
  }
] as const;

export const APP_DETAILS = {
  "ir.tv.off": {
    "id": "ir.tv.off",
    "title": "TV OFF",
    "category": "Educational",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ETV%20OFF%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EEDUCATIONAL%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EOFF%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E2.36%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package ir.tv.off appears in Educational with a 2.36 average rating.",
    "description": "Myket records this app as Educational. The local interaction sample includes 23 install events for this package, while the app metadata reports approximately 36,000 store installs.",
    "attributes": [
      "ir.tv.off",
      "Educational",
      "2.36 rating",
      "36,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "23"
      },
      {
        "label": "Store installs",
        "value": "36,000"
      },
      {
        "label": "Rating count",
        "value": "164"
      },
      {
        "label": "History role",
        "value": "User install 1 of 6"
      }
    ]
  },
  "com.farakav.anten": {
    "id": "com.farakav.anten",
    "title": "Farakav Anten",
    "category": "Utility",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23581c87%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23c026d3%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EFARAKAV%20ANTEN%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EUTILITY%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EANTEN%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.60%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package com.farakav.anten appears in Utility with a 4.60 average rating.",
    "description": "Myket records this app as Utility. The local interaction sample includes 866 install events for this package, while the app metadata reports approximately 700,000 store installs.",
    "attributes": [
      "com.farakav.anten",
      "Utility",
      "4.60 rating",
      "700,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "866"
      },
      {
        "label": "Store installs",
        "value": "700,000"
      },
      {
        "label": "Rating count",
        "value": "13,976"
      },
      {
        "label": "History role",
        "value": "User install 2 of 6"
      }
    ]
  },
  "com.incytel.mencherz": {
    "id": "com.incytel.mencherz",
    "title": "Incytel Mencherz",
    "category": "Family",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23164e63%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%230891b2%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EINCYTEL%20MENCHERZ%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EFAMILY%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EMENCHERZ%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.26%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package com.incytel.mencherz appears in Family with a 4.26 average rating.",
    "description": "Myket records this app as Family. The local interaction sample includes 1,278 install events for this package, while the app metadata reports approximately 400,000 store installs.",
    "attributes": [
      "com.incytel.mencherz",
      "Family",
      "4.26 rating",
      "400,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "1,278"
      },
      {
        "label": "Store installs",
        "value": "400,000"
      },
      {
        "label": "Rating count",
        "value": "2,926"
      },
      {
        "label": "History role",
        "value": "User install 3 of 6"
      }
    ]
  },
  "com.ParsisGames.AirCombat": {
    "id": "com.ParsisGames.AirCombat",
    "title": "Parsis Games AIR",
    "category": "Thrilling",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23581c87%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23c026d3%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EPARSIS%20GAMES%20AIR%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ETHRILLING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EAIRCOMBAT%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.70%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package com.ParsisGames.AirCombat appears in Thrilling with a 4.70 average rating.",
    "description": "Myket records this app as Thrilling. The local interaction sample includes 936 install events for this package, while the app metadata reports approximately 300,000 store installs.",
    "attributes": [
      "com.ParsisGames.AirCombat",
      "Thrilling",
      "4.70 rating",
      "300,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "936"
      },
      {
        "label": "Store installs",
        "value": "300,000"
      },
      {
        "label": "Rating count",
        "value": "7,799"
      },
      {
        "label": "History role",
        "value": "User install 4 of 6"
      }
    ]
  },
  "com.StudioBadbadak.Khastegaran": {
    "id": "com.StudioBadbadak.Khastegaran",
    "title": "Studio Badbadak Khastegaran",
    "category": "Artistic",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23164e63%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%230891b2%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ESTUDIO%20BADBADAK%20KH%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EARTISTIC%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EKHASTEGARAN%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.35%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package com.StudioBadbadak.Khastegaran appears in Artistic with a 4.35 average rating.",
    "description": "Myket records this app as Artistic. The local interaction sample includes 674 install events for this package, while the app metadata reports approximately 200,000 store installs.",
    "attributes": [
      "com.StudioBadbadak.Khastegaran",
      "Artistic",
      "4.35 rating",
      "200,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "674"
      },
      {
        "label": "Store installs",
        "value": "200,000"
      },
      {
        "label": "Rating count",
        "value": "3,019"
      },
      {
        "label": "History role",
        "value": "User install 5 of 6"
      }
    ]
  },
  "com.digikala": {
    "id": "com.digikala",
    "title": "Digikala",
    "category": "Shopping",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23581c87%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23c026d3%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EDIGIKALA%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESHOPPING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EDIGIKALA%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.49%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package com.digikala appears in Shopping with a 4.49 average rating.",
    "description": "Myket records this app as Shopping. The local interaction sample includes 2,413 install events for this package, while the app metadata reports approximately 2,000,000 store installs.",
    "attributes": [
      "com.digikala",
      "Shopping",
      "4.49 rating",
      "2,000,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "2,413"
      },
      {
        "label": "Store installs",
        "value": "2,000,000"
      },
      {
        "label": "Rating count",
        "value": "30,930"
      },
      {
        "label": "History role",
        "value": "User install 6 of 6"
      }
    ]
  },
  "com.instagram.android": {
    "id": "com.instagram.android",
    "title": "Instagram",
    "category": "Social",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%230f172a%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%231d4ed8%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EINSTAGRAM%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESOCIAL%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EANDROID%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.47%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package com.instagram.android appears in Social with a 4.47 average rating.",
    "description": "Myket records this app as Social. The local interaction sample includes 15,292 install events for this package, while the app metadata reports approximately 11,000,000 store installs.",
    "attributes": [
      "com.instagram.android",
      "Social",
      "4.47 rating",
      "11,000,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "15,292"
      },
      {
        "label": "Store installs",
        "value": "11,000,000"
      },
      {
        "label": "Rating count",
        "value": "113,194"
      },
      {
        "label": "History role",
        "value": "Recommended candidate"
      }
    ]
  },
  "ir.resaneh1.iptv": {
    "id": "ir.resaneh1.iptv",
    "title": "Resaneh 1 Iptv",
    "category": "Entertainment",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ERESANEH%201%20IPTV%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EENTERTAINMENT%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EIPTV%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.08%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package ir.resaneh1.iptv appears in Entertainment with a 4.08 average rating.",
    "description": "Myket records this app as Entertainment. The local interaction sample includes 12,143 install events for this package, while the app metadata reports approximately 3,000,000 store installs.",
    "attributes": [
      "ir.resaneh1.iptv",
      "Entertainment",
      "4.08 rating",
      "3,000,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "12,143"
      },
      {
        "label": "Store installs",
        "value": "3,000,000"
      },
      {
        "label": "Rating count",
        "value": "29,237"
      },
      {
        "label": "History role",
        "value": "Recommended candidate"
      }
    ]
  },
  "com.tencent.ig": {
    "id": "com.tencent.ig",
    "title": "Tencent IG",
    "category": "Thrilling",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%230f172a%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%231d4ed8%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ETENCENT%20IG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ETHRILLING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EIG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.51%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package com.tencent.ig appears in Thrilling with a 4.51 average rating.",
    "description": "Myket records this app as Thrilling. The local interaction sample includes 7,919 install events for this package, while the app metadata reports approximately 3,000,000 store installs.",
    "attributes": [
      "com.tencent.ig",
      "Thrilling",
      "4.51 rating",
      "3,000,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "7,919"
      },
      {
        "label": "Store installs",
        "value": "3,000,000"
      },
      {
        "label": "Rating count",
        "value": "81,808"
      },
      {
        "label": "History role",
        "value": "Recommended candidate"
      }
    ]
  },
  "com.ForgeGames.SpecialForcesGroup2": {
    "id": "com.ForgeGames.SpecialForcesGroup2",
    "title": "Forge Games Special",
    "category": "Thrilling",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%237c2d12%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ea580c%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EFORGE%20GAMES%20SPECIA%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ETHRILLING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3ESPECIALFORCESGROUP2%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.47%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package com.ForgeGames.SpecialForcesGroup2 appears in Thrilling with a 4.47 average rating.",
    "description": "Myket records this app as Thrilling. The local interaction sample includes 7,797 install events for this package, while the app metadata reports approximately 3,000,000 store installs.",
    "attributes": [
      "com.ForgeGames.SpecialForcesGroup2",
      "Thrilling",
      "4.47 rating",
      "3,000,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "7,797"
      },
      {
        "label": "Store installs",
        "value": "3,000,000"
      },
      {
        "label": "Rating count",
        "value": "52,152"
      },
      {
        "label": "History role",
        "value": "Recommended candidate"
      }
    ]
  },
  "ir.nomogame.ClutchGame": {
    "id": "ir.nomogame.ClutchGame",
    "title": "Nomogame Clutch Game",
    "category": "Driving",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%2314532d%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2316a34a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ENOMOGAME%20CLUTCH%20GA%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EDRIVING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3ECLUTCHGAME%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.57%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package ir.nomogame.ClutchGame appears in Driving with a 4.57 average rating.",
    "description": "Myket records this app as Driving. The local interaction sample includes 6,193 install events for this package, while the app metadata reports approximately 2,000,000 store installs.",
    "attributes": [
      "ir.nomogame.ClutchGame",
      "Driving",
      "4.57 rating",
      "2,000,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "6,193"
      },
      {
        "label": "Store installs",
        "value": "2,000,000"
      },
      {
        "label": "Rating count",
        "value": "37,100"
      },
      {
        "label": "History role",
        "value": "Recommended candidate"
      }
    ]
  },
  "ir.medu.shad": {
    "id": "ir.medu.shad",
    "title": "Medu Shad",
    "category": "Educational",
    "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EMEDU%20SHAD%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EEDUCATIONAL%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3ESHAD%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E2.17%20rating%3C/text%3E%0A%3C/svg%3E",
    "subtitle": "Package ir.medu.shad appears in Educational with a 2.17 average rating.",
    "description": "Myket records this app as Educational. The local interaction sample includes 4,673 install events for this package, while the app metadata reports approximately 3,000,000 store installs.",
    "attributes": [
      "ir.medu.shad",
      "Educational",
      "2.17 rating",
      "3,000,000 installs"
    ],
    "facts": [
      {
        "label": "Sample installs",
        "value": "4,673"
      },
      {
        "label": "Store installs",
        "value": "3,000,000"
      },
      {
        "label": "Rating count",
        "value": "31,389"
      },
      {
        "label": "History role",
        "value": "Recommended candidate"
      }
    ]
  }
} as const;

export const RECOMMENDATIONS = {
  "popularity": [
    {
      "id": "com.instagram.android",
      "title": "Instagram",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%230f172a%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%231d4ed8%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EINSTAGRAM%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESOCIAL%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EANDROID%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.47%20rating%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Installed 15,292 times in the Myket sample. Metadata places it in Social with 11,000,000 approximate store installs.",
      "score": "15,292",
      "scoreLabel": "Sample installs",
      "signals": [
        {
          "label": "Install idx",
          "value": 100,
          "color": "bg-emerald-500"
        },
        {
          "label": "Category fit",
          "value": 35,
          "color": "bg-zinc-300"
        },
        {
          "label": "Rating",
          "value": 89,
          "color": "bg-amber-500"
        }
      ],
      "tags": [
        {
          "label": "Top installs",
          "type": "popularity"
        }
      ]
    },
    {
      "id": "ir.resaneh1.iptv",
      "title": "Resaneh 1 Iptv",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ERESANEH%201%20IPTV%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EENTERTAINMENT%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EIPTV%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.08%20rating%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Installed 12,143 times in the Myket sample. Metadata places it in Entertainment with 3,000,000 approximate store installs.",
      "score": "12,143",
      "scoreLabel": "Sample installs",
      "signals": [
        {
          "label": "Install idx",
          "value": 79,
          "color": "bg-emerald-500"
        },
        {
          "label": "Category fit",
          "value": 35,
          "color": "bg-zinc-300"
        },
        {
          "label": "Rating",
          "value": 82,
          "color": "bg-amber-500"
        }
      ],
      "tags": [
        {
          "label": "Top installs",
          "type": "popularity"
        }
      ]
    },
    {
      "id": "com.tencent.ig",
      "title": "Tencent IG",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%230f172a%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%231d4ed8%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ETENCENT%20IG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ETHRILLING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EIG%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.51%20rating%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Installed 7,919 times in the Myket sample. Metadata places it in Thrilling with 3,000,000 approximate store installs.",
      "score": "7,919",
      "scoreLabel": "Sample installs",
      "signals": [
        {
          "label": "Install idx",
          "value": 52,
          "color": "bg-emerald-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        },
        {
          "label": "Rating",
          "value": 90,
          "color": "bg-amber-500"
        }
      ],
      "tags": [
        {
          "label": "Top installs",
          "type": "popularity"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "com.ForgeGames.SpecialForcesGroup2",
      "title": "Forge Games Special",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%237c2d12%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ea580c%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EFORGE%20GAMES%20SPECIA%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ETHRILLING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3ESPECIALFORCESGROUP2%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.47%20rating%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Installed 7,797 times in the Myket sample. Metadata places it in Thrilling with 3,000,000 approximate store installs.",
      "score": "7,797",
      "scoreLabel": "Sample installs",
      "signals": [
        {
          "label": "Install idx",
          "value": 51,
          "color": "bg-emerald-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        },
        {
          "label": "Rating",
          "value": 89,
          "color": "bg-amber-500"
        }
      ],
      "tags": [
        {
          "label": "Top installs",
          "type": "popularity"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "ir.nomogame.ClutchGame",
      "title": "Nomogame Clutch Game",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%2314532d%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2316a34a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ENOMOGAME%20CLUTCH%20GA%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EDRIVING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3ECLUTCHGAME%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.57%20rating%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Installed 6,193 times in the Myket sample. Metadata places it in Driving with 2,000,000 approximate store installs.",
      "score": "6,193",
      "scoreLabel": "Sample installs",
      "signals": [
        {
          "label": "Install idx",
          "value": 40,
          "color": "bg-emerald-500"
        },
        {
          "label": "Category fit",
          "value": 35,
          "color": "bg-zinc-300"
        },
        {
          "label": "Rating",
          "value": 91,
          "color": "bg-amber-500"
        }
      ],
      "tags": [
        {
          "label": "Top installs",
          "type": "popularity"
        }
      ]
    }
  ],
  "item_item": [
    {
      "id": "com.ForgeGames.SpecialForcesGroup2",
      "title": "Forge Games Special",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%237c2d12%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ea580c%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EFORGE%20GAMES%20SPECIA%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ETHRILLING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3ESPECIALFORCESGROUP2%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.47%20rating%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Installed by 1,556 users who also installed apps from this user's history, matching 6 of the 6 seed apps.",
      "score": "1,556",
      "scoreLabel": "Co-users",
      "signals": [
        {
          "label": "Co-user idx",
          "value": 100,
          "color": "bg-blue-500"
        },
        {
          "label": "Seed overlap",
          "value": 100,
          "color": "bg-indigo-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        }
      ],
      "tags": [
        {
          "label": "6/6 seed overlap",
          "type": "coview"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    },
    {
      "id": "ir.resaneh1.iptv",
      "title": "Resaneh 1 Iptv",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ERESANEH%201%20IPTV%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EENTERTAINMENT%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EIPTV%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.08%20rating%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Installed by 1,527 users who also installed apps from this user's history, matching 6 of the 6 seed apps.",
      "score": "1,527",
      "scoreLabel": "Co-users",
      "signals": [
        {
          "label": "Co-user idx",
          "value": 98,
          "color": "bg-blue-500"
        },
        {
          "label": "Seed overlap",
          "value": 100,
          "color": "bg-indigo-500"
        },
        {
          "label": "Category fit",
          "value": 35,
          "color": "bg-zinc-300"
        }
      ],
      "tags": [
        {
          "label": "6/6 seed overlap",
          "type": "coview"
        }
      ]
    },
    {
      "id": "com.instagram.android",
      "title": "Instagram",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%230f172a%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%231d4ed8%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EINSTAGRAM%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3ESOCIAL%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3EANDROID%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.47%20rating%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Installed by 1,414 users who also installed apps from this user's history, matching 6 of the 6 seed apps.",
      "score": "1,414",
      "scoreLabel": "Co-users",
      "signals": [
        {
          "label": "Co-user idx",
          "value": 91,
          "color": "bg-blue-500"
        },
        {
          "label": "Seed overlap",
          "value": 100,
          "color": "bg-indigo-500"
        },
        {
          "label": "Category fit",
          "value": 35,
          "color": "bg-zinc-300"
        }
      ],
      "tags": [
        {
          "label": "6/6 seed overlap",
          "type": "coview"
        }
      ]
    },
    {
      "id": "ir.nomogame.ClutchGame",
      "title": "Nomogame Clutch Game",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%2314532d%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2316a34a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3ENOMOGAME%20CLUTCH%20GA%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EDRIVING%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3ECLUTCHGAME%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E4.57%20rating%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Installed by 1,391 users who also installed apps from this user's history, matching 6 of the 6 seed apps.",
      "score": "1,391",
      "scoreLabel": "Co-users",
      "signals": [
        {
          "label": "Co-user idx",
          "value": 89,
          "color": "bg-blue-500"
        },
        {
          "label": "Seed overlap",
          "value": 100,
          "color": "bg-indigo-500"
        },
        {
          "label": "Category fit",
          "value": 35,
          "color": "bg-zinc-300"
        }
      ],
      "tags": [
        {
          "label": "6/6 seed overlap",
          "type": "coview"
        }
      ]
    },
    {
      "id": "ir.medu.shad",
      "title": "Medu Shad",
      "image": "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%22320%22%20height%3D%22320%22%20viewBox%3D%220%200%20320%20320%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22g%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%22100%25%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%233f3f46%22%20/%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%2371717a%22%20/%3E%0A%20%20%20%20%3C/linearGradient%3E%0A%20%20%3C/defs%3E%0A%20%20%3Crect%20width%3D%22320%22%20height%3D%22320%22%20rx%3D%2232%22%20fill%3D%22url%28%23g%29%22%20/%3E%0A%20%20%3Crect%20x%3D%2220%22%20y%3D%2220%22%20width%3D%22280%22%20height%3D%22280%22%20rx%3D%2224%22%20fill%3D%22rgba%28255%2C255%2C255%2C0.08%29%22%20stroke%3D%22rgba%28255%2C255%2C255%2C0.18%29%22%20/%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%2292%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2222%22%20font-weight%3D%22700%22%20fill%3D%22%23f8fafc%22%3EMEDU%20SHAD%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22128%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23e2e8f0%22%3EEDUCATIONAL%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22220%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2225%22%20font-weight%3D%22700%22%20fill%3D%22%23ffffff%22%3ESHAD%3C/text%3E%0A%20%20%3Ctext%20x%3D%2236%22%20y%3D%22258%22%20font-family%3D%22Arial%2C%20sans-serif%22%20font-size%3D%2218%22%20font-weight%3D%22600%22%20fill%3D%22%23dbeafe%22%3E2.17%20rating%3C/text%3E%0A%3C/svg%3E",
      "explanation": "Installed by 1,314 users who also installed apps from this user's history, matching 6 of the 6 seed apps.",
      "score": "1,314",
      "scoreLabel": "Co-users",
      "signals": [
        {
          "label": "Co-user idx",
          "value": 84,
          "color": "bg-blue-500"
        },
        {
          "label": "Seed overlap",
          "value": 100,
          "color": "bg-indigo-500"
        },
        {
          "label": "Category fit",
          "value": 100,
          "color": "bg-cyan-500"
        }
      ],
      "tags": [
        {
          "label": "6/6 seed overlap",
          "type": "coview"
        },
        {
          "label": "Same category",
          "type": "category"
        }
      ]
    }
  ]
} as const;

export const HOW_IT_WORKS_STEPS = [
  {
    "title": "Replay one real install history",
    "body": "The left rail replays 6 app installs from one anonymized Myket user in timestamp order."
  },
  {
    "title": "Compare two ranking methods",
    "body": "Popularity ranks apps by total installs in the sample, while Item-Item CF ranks apps by how often they were installed by users who also installed this user's apps."
  },
  {
    "title": "Keep the graph path open",
    "body": "The underlying data is a user-app-time interaction graph, which maps directly to PyTorch Geometric for a future LightGCN or graph-embedding inference layer."
  }
] as const;

export const MODEL_EXPLANATIONS = [
  {
    "id": "popularity",
    "title": "Popularity",
    "eyebrow": "Install volume",
    "summary": "A global baseline that sorts Android apps by total install interactions across the Myket sample.",
    "signals": [
      "Sample installs",
      "Category fit",
      "Rating"
    ]
  },
  {
    "id": "item_item",
    "title": "Item-Item CF",
    "eyebrow": "Co-install graph",
    "summary": "A behavioral model that ranks apps by how often they appear in the same users' install histories as the selected user's apps.",
    "signals": [
      "Co-user count",
      "Seed overlap",
      "Category fit"
    ]
  }
] as const;

export default {
  DEMO_META,
  HISTORY,
  APP_DETAILS,
  RECOMMENDATIONS,
  HOW_IT_WORKS_STEPS,
  MODEL_EXPLANATIONS,
} as const;
